Added the Feb, March and April meetup details
Chennaipy/talks pull request #27
Opened 2017-04-23 10:43 UTC by dragsubil

2017-04-23 10:55 UTC, igauravsehrawat commented
We should add slides and videos(if any).

2017-04-23 10:56 UTC, igauravsehrawat requested changes

2017-04-23 10:56 UTC, igauravsehrawat commented on README.md
> +##### Iteration Protocol in Python
This talk didn't happen.

2017-04-23 12:37 UTC, dragsubil commented on README.md
> +##### Iteration Protocol in Python
I couldn't find any other links to slides or videos (besides Vijay's Dropbox link).

> This talk didn't happen.

Will remove it pronto.

2017-04-23 17:18 UTC, igauravsehrawat commented on README.md
> +##### Iteration Protocol in Python
Ok. I have asked speakers on meetup to provide link to slides.
Apart from that LGTM.
@bravegnu Can you give link for your talk recording?

Thanks

2017-04-24 06:22 UTC, shrayasr commented
@igauravsehrawat let's merge this and @dragsubil can open another PR when the links come through?

2017-04-24 06:31 UTC, igauravsehrawat commented
@shrayasr Yeah.

2017-04-24 06:39 UTC, dragsubil commented
Okay by me
On 24 Apr 2017 12:01 pm, "Gaurav" <notifications@github.com> wrote:

> @shrayasr <https://github.com/shrayasr> Yeah.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Chennaipy/talks/pull/27#issuecomment-296538181>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AQgjZl1lmItZ2dlaTSj0mfbXzq_JVlK3ks5rzEG9gaJpZM4NFXn_>
> .
>

2017-04-24 10:51 UTC, merged

2017-04-24 10:51 UTC, shrayasr commented
Awesome, thanks @dragsubil and @igauravsehrawat 

:shipit: 🚢

2017-04-25 05:14 UTC, igauravsehrawat commented
Thanks @dragsubil

2017-04-25 05:19 UTC, dragsubil commented
Thank you too!
On 25 Apr 2017 10:44 am, "Gaurav" <notifications@github.com> wrote:

> Thanks @dragsubil <https://github.com/dragsubil>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Chennaipy/talks/pull/27#issuecomment-296910796>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AQgjZmE_9DdelikJyE277aKLfDeUxZkbks5rzYEfgaJpZM4NFXn_>
> .
>